# theme: jekyll-theme-architect
theme: jekylle-theme-cayman
# theme: jekylle-theme-dinky
# theme: jekylle-theme-hacker
# theme: jekylle-theme-leap day
# theme: jekylle-theme-merlot
# theme: jekylle-theme-midnight
# theme: jekylle-theme-minima
# theme: jekylle-theme-minimal
# theme: jekylle-theme-modernist
# theme: jekylle-theme-slate
# theme: jekylle-theme-tactile
# theme: jekylle-theme-time machine


title: PLAZMA's Stdout
description: The stdout of my concionceness. Where I share the things I'm learning and discovering, my thoughts about life, and more.
