# theme: jekyll-theme-architect
# theme: jekyll-theme-cayman
# theme: jekyll-theme-dinky
# theme: jekyll-theme-hacker
# theme: jekyll-theme-leap day
# theme: jekyll-theme-merlot
# theme: jekyll-theme-midnight
# theme: jekyll-theme-minima
# theme: jekyll-theme-modernist
# theme: jekyll-theme-slate
theme: jekyll-theme-tactile


title: PLAZMA's Stdout
description: The stdout of my concionceness. Where I share the things I'm learning and discovering, my thoughts about life, and more.
